spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abuergo/E-commerce-JavaBackend-Project-Config-Properties
server:
  port: 8888